services:
  - type: web
    name: endodetect-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python website/backend/app.py
    port: 5000
    instances: 1
    autoDeploy: true
