services:
  - type: web
    name: endodetect-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn website.backend.app:app
    port: 5000
    instances: 1
    autoDeploy: true
    pythonVersion: 
